spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test;AUTO_SERVER=TRUE
#    username: sa
#    password: sa1234
#    driverClassName: org.h2.Driver
  datasource:
    url: "jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:avail_test}"
    username: ${DB_USER:postgres}
    password: ${DB_PASS:abcd#1234}
    hikari:
      connection-timeout: 20000
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 10000
      pool-name: primary
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl