spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;AUTO_SERVER=TRUE
    username: sa
    password: sa1234
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl